import assert from "node:assert/strict";
import test from "node:test";
import bcrypt from "bcryptjs";
import { Prisma, PrismaClient } from "@prisma/client";
import { changeOrderAdminNotes, changeOrderQuote, changeOrderStatus } from "./operations";
import { canTransitionOrderStatus } from "./policy";
import { parseOrdersPage, quoteUpdateSchema, statusUpdateSchema } from "./validation";
import { findClientOrder } from "@/features/orders/queries";

const prisma=new PrismaClient();
test("politique, validation des filtres et montants",()=>{assert.equal(canTransitionOrderStatus("NEW","UNDER_REVIEW"),true);assert.equal(canTransitionOrderStatus("NEW","ACCEPTED"),false);assert.equal(statusUpdateSchema.safeParse({id:"invalide",status:"HACKED"}).success,false);assert.equal(quoteUpdateSchema.safeParse({id:"invalide",quotedAmount:"-1"}).success,false);assert.equal(quoteUpdateSchema.safeParse({id:"invalide",quotedAmount:"abc"}).success,false);assert.equal(parseOrdersPage("2"),2);assert.equal(parseOrdersPage("-4"),1);assert.equal(parseOrdersPage("999999999"),1);});

test("modifications Admin auditées, isolées et protégées contre la concurrence",async()=>{const suffix=Date.now().toString();const ids:{admin?:string;client?:string;service?:string;order?:string}={};try{const hash=await bcrypt.hash("PasswordTest123!",4);const admin=await prisma.user.create({data:{name:"Admin audit test",phone:`+24390${suffix.slice(-8)}`,passwordHash:hash,role:"ADMIN"}});ids.admin=admin.id;const client=await prisma.user.create({data:{name:"Client audit test",phone:`+24391${suffix.slice(-8)}`,passwordHash:hash,role:"CLIENT"}});ids.client=client.id;const service=await prisma.service.create({data:{name:"Service audit test",slug:`audit-test-${suffix}`,shortDescription:"Test",description:"Test",category:"Test",priceType:"QUOTE"}});ids.service=service.id;const order=await prisma.order.create({data:{orderNumber:`AUDIT-${suffix}`,clientId:client.id,serviceId:service.id,title:"Commande audit",description:"Commande utilisée pour tester l’audit.",currency:"USD",adminNotes:"secret initial"}});ids.order=order.id;
await changeOrderStatus(admin.id,order.id,"UNDER_REVIEW");assert.equal((await prisma.order.findUniqueOrThrow({where:{id:order.id}})).status,"UNDER_REVIEW");await assert.rejects(changeOrderStatus(admin.id,order.id,"ACCEPTED"));await assert.rejects(changeOrderStatus(admin.id,"clxxxxxxxxxxxxxxxxxxxxxxxxx","UNDER_REVIEW"));await changeOrderQuote(admin.id,order.id,new Prisma.Decimal("1250.50"));await changeOrderAdminNotes(admin.id,order.id,"Note interne test");const updated=await prisma.order.findUniqueOrThrow({where:{id:order.id},include:{auditLogs:true}});assert.equal(updated.quotedAmount?.toFixed(2),"1250.50");assert.equal(updated.adminNotes,"Note interne test");assert.equal(updated.auditLogs.filter(log=>log.action==="ORDER_STATUS_CHANGED").length,1);assert.equal(updated.auditLogs.filter(log=>log.action==="ORDER_QUOTE_UPDATED").length,1);assert.equal(updated.auditLogs.filter(log=>log.action==="ORDER_ADMIN_NOTES_UPDATED").length,1);const clientView=await findClientOrder(client.id,order.id);assert.ok(clientView);assert.equal("adminNotes" in clientView,false);assert.equal("passwordHash" in clientView,false);
const concurrent=await Promise.allSettled([changeOrderStatus(admin.id,order.id,"QUOTED"),changeOrderStatus(admin.id,order.id,"NEEDS_INFORMATION")]);assert.equal(concurrent.filter(result=>result.status==="fulfilled").length,1);const statusAudits=await prisma.orderAuditLog.count({where:{orderId:order.id,action:"ORDER_STATUS_CHANGED"}});assert.equal(statusAudits,2);
}finally{if(ids.order)await prisma.order.deleteMany({where:{id:ids.order}});if(ids.service)await prisma.service.deleteMany({where:{id:ids.service}});await prisma.user.deleteMany({where:{id:{in:[ids.admin,ids.client].filter((id):id is string=>Boolean(id))}}});}});
test.after(async()=>{await prisma.$disconnect()});
