import assert from "node:assert/strict";
import test from "node:test";
import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";
import { createOrderByAdmin } from "./create-operation";
import { createAdminOrderSchema } from "./create-validation";
import { findClientOrder } from "@/features/orders/queries";

const prisma=new PrismaClient();
const common={serviceId:"",title:"Commande manuelle test",description:"Description suffisamment longue pour tester une commande manuelle.",companyName:"",budget:"500",currency:"usd",desiredDeadline:""};
function parsed(input:Record<string,unknown>){return createAdminOrderSchema.parse(input)}

test("la validation Admin refuse WEBSITE et ignore les champs imposés",()=>{const result=createAdminOrderSchema.safeParse({...common,source:"WEBSITE",clientMode:"EXISTING",clientId:"clx1234567890123456789012",status:"ACCEPTED",quotedAmount:"1",adminId:"injecté"});assert.equal(result.success,false);const accepted=createAdminOrderSchema.safeParse({...common,source:"ADMIN",clientMode:"EXISTING",clientId:"clx1234567890123456789012",status:"ACCEPTED",quotedAmount:"1",adminId:"injecté"});if(accepted.success){assert.equal("status" in accepted.data,false);assert.equal("quotedAmount" in accepted.data,false);assert.equal("adminId" in accepted.data,false)}});

test("création Admin pour Client existant/nouveau, audit, isolation et rollback",async()=>{const suffix=Date.now().toString();const ids:{users:string[];services:string[];orders:string[]}={users:[],services:[],orders:[]};try{const fixtureHash=await bcrypt.hash("FixturePassword123!",4);const admin=await prisma.user.create({data:{name:"Admin création test",phone:`+24392${suffix.slice(-8)}`,passwordHash:fixtureHash,role:"ADMIN"}});ids.users.push(admin.id);const existing=await prisma.user.create({data:{name:"Client existant test",phone:`+24393${suffix.slice(-8)}`,passwordHash:fixtureHash,role:"CLIENT"}});ids.users.push(existing.id);const other=await prisma.user.create({data:{name:"Autre Client test",phone:`+24394${suffix.slice(-8)}`,passwordHash:fixtureHash,role:"CLIENT"}});ids.users.push(other.id);const otherAdmin=await prisma.user.create({data:{name:"Admin non client",phone:`+24395${suffix.slice(-8)}`,passwordHash:fixtureHash,role:"ADMIN"}});ids.users.push(otherAdmin.id);const active=await prisma.service.create({data:{name:"Service manuel test",slug:`manual-${suffix}`,shortDescription:"Test",description:"Test",category:"Test",priceType:"QUOTE"}});ids.services.push(active.id);const inactive=await prisma.service.create({data:{name:"Service manuel inactif",slug:`manual-off-${suffix}`,shortDescription:"Test",description:"Test",category:"Test",priceType:"QUOTE",isActive:false}});ids.services.push(inactive.id);
const whatsapp=await createOrderByAdmin(admin.id,parsed({...common,serviceId:active.id,source:"WHATSAPP",clientMode:"EXISTING",clientId:existing.id}));ids.orders.push(whatsapp.id);const direct=await createOrderByAdmin(admin.id,parsed({...common,serviceId:active.id,source:"ADMIN",clientMode:"EXISTING",clientId:existing.id,title:"Commande directe"}));ids.orders.push(direct.id);const newPhone=`+24396${suffix.slice(-8)}`;const temporaryPassword="TemporaryPassword123!";const created=await createOrderByAdmin(admin.id,parsed({...common,serviceId:active.id,source:"WHATSAPP",clientMode:"NEW",clientName:"Nouveau Client test",clientEmail:"",clientPhone:newPhone,temporaryPassword}));ids.orders.push(created.id);const newUser=await prisma.user.findUniqueOrThrow({where:{phone:newPhone}});ids.users.push(newUser.id);assert.equal(newUser.role,"CLIENT");assert.equal(newUser.isActive,true);assert.equal(await bcrypt.compare(temporaryPassword,newUser.passwordHash),true);const orders=await prisma.order.findMany({where:{id:{in:ids.orders}},include:{auditLogs:true}});assert.equal(new Set(orders.map(order=>order.orderNumber)).size,3);assert.ok(orders.every(order=>order.status==="NEW"));assert.ok(orders.every(order=>order.auditLogs.some(log=>log.action==="ORDER_CREATED_BY_ADMIN"&&log.adminId===admin.id&&log.newValue===order.source)));const savedHash=newUser.passwordHash;await assert.rejects(createOrderByAdmin(admin.id,parsed({...common,serviceId:active.id,source:"ADMIN",clientMode:"NEW",clientName:"Doublon",clientEmail:`new-${suffix}@example.com`,clientPhone:newPhone,temporaryPassword:"DifferentPassword123!"})));assert.equal((await prisma.user.findUniqueOrThrow({where:{phone:newPhone}})).passwordHash,savedHash);await assert.rejects(createOrderByAdmin(admin.id,parsed({...common,serviceId:active.id,source:"ADMIN",clientMode:"EXISTING",clientId:otherAdmin.id})));await assert.rejects(createOrderByAdmin(admin.id,parsed({...common,serviceId:inactive.id,source:"ADMIN",clientMode:"EXISTING",clientId:existing.id})));const clientView=await findClientOrder(existing.id,whatsapp.id);assert.ok(clientView);assert.equal(await findClientOrder(other.id,whatsapp.id),null);assert.equal("adminNotes" in clientView,false);assert.equal("auditLogs" in clientView,false);
const rollbackPhone=`+24397${suffix.slice(-8)}`;await assert.rejects(createOrderByAdmin("clinvalidadmin000000000000",parsed({...common,serviceId:active.id,source:"ADMIN",clientMode:"NEW",clientName:"Rollback Client",clientEmail:`rollback-${suffix}@example.com`,clientPhone:rollbackPhone,temporaryPassword:"RollbackPassword123!"})));assert.equal(await prisma.user.count({where:{phone:rollbackPhone}}),0);
}finally{await prisma.order.deleteMany({where:{id:{in:ids.orders}}});await prisma.service.deleteMany({where:{id:{in:ids.services}}});await prisma.user.deleteMany({where:{id:{in:ids.users}}});}});
test.after(async()=>{await prisma.$disconnect()});
