"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin, requireClient } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";
import { createRequestSchema, updateRequestSchema } from "@/features/modification-requests/validation";
import type { RequestActionState } from "@/features/modification-requests/types";
const values=(f:FormData)=>Object.fromEntries(f.entries());
export async function createModificationRequest(_:RequestActionState,f:FormData):Promise<RequestActionState>{const client=await requireClient();const p=createRequestSchema.safeParse(values(f));if(!p.success)return{status:"error",message:p.error.issues[0]?.message};const version=await prisma.projectVersion.findFirst({where:{id:p.data.versionId,projectId:p.data.projectId,project:{clientId:client.id}},select:{id:true}});if(!version)return{status:"error",message:"Version introuvable."};await prisma.modificationRequest.create({data:{versionId:version.id,clientId:client.id,title:p.data.title,description:p.data.description}});revalidatePath(`/client/projects/${p.data.projectId}/versions/${version.id}`);return{status:"success",message:"Votre demande a été envoyée."};}
export async function updateModificationRequest(_:RequestActionState,f:FormData):Promise<RequestActionState>{await requireAdmin();const p=updateRequestSchema.safeParse(values(f));if(!p.success)return{status:"error",message:"Informations invalides."};const request=await prisma.modificationRequest.findUnique({where:{id:p.data.id},select:{id:true}});if(!request)return{status:"error",message:"Demande introuvable."};const resolvedAt=["COMPLETED","REJECTED"].includes(p.data.status)?new Date():null;await prisma.modificationRequest.update({where:{id:request.id},data:{status:p.data.status,adminResponse:p.data.adminResponse,resolvedAt}});revalidatePath("/admin");revalidatePath("/admin/requests");revalidatePath(`/admin/requests/${request.id}`);return{status:"success",message:"Demande mise à jour."};}
