"use client";

import { useActionState } from "react";
import type { OrderStatus } from "@prisma/client";
import { updateOrderAdminNotes, updateOrderQuote, updateOrderStatus } from "@/features/admin-orders/actions";
import { initialAdminOrderActionState } from "@/features/admin-orders/types";
import { orderStatusLabels } from "@/features/orders/labels";
import { orderStatusTransitions } from "@/features/admin-orders/policy";

function Message({state}:{state:{status:string;message?:string}}){return state.status!=="idle"?<p role="status" className={`mt-3 text-sm ${state.status==="success"?"text-electric-mint":"text-red-300"}`}>{state.message}</p>:null}
export function StatusForm({id,status}:{id:string;status:OrderStatus}){const[state,action,pending]=useActionState(updateOrderStatus,initialAdminOrderActionState);const options=orderStatusTransitions[status];return <form action={action}><input type="hidden" name="id" value={id}/><label className="text-sm font-medium">Nouveau statut<select name="status" required defaultValue="" className="mt-2 w-full rounded-xl border border-white/15 bg-graphite px-4 py-3"><option value="" disabled>Sélectionner</option>{options.map(value=><option key={value} value={value}>{orderStatusLabels[value]}</option>)}</select></label><button disabled={pending||!options.length} className="mt-4 rounded-xl bg-electric-mint px-4 py-2 font-bold text-graphite disabled:opacity-50">{pending?"Mise à jour…":"Modifier le statut"}</button><Message state={state}/></form>}
export function QuoteForm({id,amount,currency}:{id:string;amount:string|null;currency:string}){const[state,action,pending]=useActionState(updateOrderQuote,initialAdminOrderActionState);return <form action={action}><input type="hidden" name="id" value={id}/><label className="text-sm font-medium">Montant proposé ({currency})<input required name="quotedAmount" inputMode="decimal" pattern="\d{1,10}([.]\d{1,2})?" defaultValue={amount??""} className="mt-2 w-full rounded-xl border border-white/15 bg-graphite px-4 py-3"/></label><button disabled={pending} className="mt-4 rounded-xl bg-electric-mint px-4 py-2 font-bold text-graphite">Enregistrer le montant</button><Message state={state}/></form>}
export function NotesForm({id,notes}:{id:string;notes:string|null}){const[state,action,pending]=useActionState(updateOrderAdminNotes,initialAdminOrderActionState);return <form action={action}><input type="hidden" name="id" value={id}/><label className="text-sm font-medium">Notes Admin internes<textarea name="adminNotes" maxLength={5000} rows={7} defaultValue={notes??""} className="mt-2 w-full rounded-xl border border-white/15 bg-graphite px-4 py-3"/></label><p className="mt-2 text-xs text-muted">Ces notes ne sont jamais visibles par le Client.</p><button disabled={pending} className="mt-4 rounded-xl bg-electric-mint px-4 py-2 font-bold text-graphite">Enregistrer les notes</button><Message state={state}/></form>}
