import Link from"next/link";import{notFound}from"next/navigation";import{prisma}from"@/lib/prisma";import{projectIdSchema}from"@/features/projects/validation";import{projectStatusLabels}from"@/features/projects/labels";import{MarkDeliveredForm}from"./mark-delivered-form";
export default async function Page({params}:{params:Promise<{id:string}>}){
 const parsed=projectIdSchema.safeParse((await params).id);if(!parsed.success)notFound();
 const p=await prisma.project.findUnique({where:{id:parsed.data},include:{
  client:{select:{name:true,phone:true}},payments:{where:{type:"FINAL"},orderBy:{createdAt:"desc"},take:1,select:{status:true}},
  versions:{orderBy:{versionNumber:"desc"},select:{id:true,versionNumber:true,name:true,status:true,deliverables:{select:{finalKind:true}},_count:{select:{deliverables:true}}}}
 }});if(!p)notFound();const latest=p.versions[0];const hasFinal=latest?.deliverables.some(d=>d.finalKind);
 return <main className="mx-auto max-w-4xl px-6 py-12 text-white"><Link href="/admin/projects" className="text-electric-mint">← Projets</Link><h1 className="mt-6 text-4xl font-bold">{p.name}</h1><p className="mt-2 text-muted">{p.client.name} · {projectStatusLabels[p.status]}</p><section className="mt-10 rounded-2xl border border-electric-mint/30 bg-graphite-secondary p-6"><p className="text-sm font-bold tracking-[.18em] text-electric-mint">LIVRAISON</p><h2 className="mt-2 text-2xl font-bold">{p.status==="DELIVERED"?"Projet livré":p.status==="PAYMENT_PENDING"?"Paiement non validé.":p.status==="READY_FOR_DELIVERY"?"Paiement validé — préparer la livraison.":"Livraison non disponible"}</h2>{p.deliveredAt&&<p className="mt-2 text-muted">Livré le {p.deliveredAt.toLocaleString("fr-FR")}</p>}{hasFinal&&<p className="mt-2 text-electric-mint">Final prêt.</p>}{latest&&<Link href={`/admin/projects/${p.id}/versions/${latest.id}`} className="mt-4 block text-electric-mint underline">Ouvrir la version finale</Link>}{p.status==="READY_FOR_DELIVERY"&&p.payments[0]?.status==="PAID"&&hasFinal&&<MarkDeliveredForm projectId={p.id}/>}</section><section className="mt-10"><div className="flex justify-between"><h2 className="text-2xl font-bold">Versions</h2><Link href={`/admin/projects/${p.id}/versions/new`} className="rounded-xl bg-electric-mint px-4 py-2 text-graphite">+ Nouvelle version</Link></div>{p.versions.map(v=><Link key={v.id} href={`/admin/projects/${p.id}/versions/${v.id}`} className="mt-3 flex justify-between rounded-xl border border-white/10 p-5"><strong>Version {v.versionNumber} — {v.name}</strong><span>{v._count.deliverables} livrable(s) · {v.status}</span></Link>)}</section></main>
}
