"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/guards";
import type { ActionState } from "@/features/versions/types";
import { previewMetadataSchema, previewReferenceSchema } from "./validation";
import { DeliverablePreviewError, saveVideoPreview, saveWebsitePreview } from "./operations";

function refresh(projectId:string,versionId:string){revalidatePath(`/admin/projects/${projectId}`);revalidatePath(`/admin/projects/${projectId}/versions/${versionId}`);revalidatePath(`/client/projects/${projectId}`);revalidatePath(`/client/projects/${projectId}/versions/${versionId}`)}
const safeValidationMessages=["Fichier preview requis.","Le fichier est vide.","Le fichier dépasse la taille maximale autorisée.","Seuls les fichiers MP4 et WEBM sont autorisés.","L’extension ne correspond pas au type vidéo annoncé.","Protocole d’URL interdit.","HTTPS est obligatoire en production."];
function errorState(error:unknown):ActionState{const message=error instanceof DeliverablePreviewError?error.message:error instanceof Error&&safeValidationMessages.includes(error.message)?error.message:"L’enregistrement de la preview a échoué.";return{status:"error",message}}
export async function uploadVideoPreview(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const reference=previewReferenceSchema.safeParse(Object.fromEntries(formData.entries()));const metadata=previewMetadataSchema.safeParse(Object.fromEntries(formData.entries()));if(!reference.success||!metadata.success)return{status:"error",message:"Informations invalides."};const file=formData.get("previewFile");if(!(file instanceof File))return{status:"error",message:"Fichier preview requis."};try{const saved=await saveVideoPreview(reference.data.projectId,reference.data.versionId,metadata.data,file,reference.data.deliverableId);refresh(reference.data.projectId,reference.data.versionId);return{status:"success",message:reference.data.deliverableId?"Preview vidéo remplacée.":"Preview vidéo ajoutée.",id:saved.id}}catch(error){return errorState(error)}}
export async function saveWebsitePreviewAction(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const reference=previewReferenceSchema.safeParse(Object.fromEntries(formData.entries()));const metadata=previewMetadataSchema.safeParse(Object.fromEntries(formData.entries()));const previewUrl=formData.get("previewUrl");if(!reference.success||!metadata.success||typeof previewUrl!=="string")return{status:"error",message:"Informations invalides."};try{const saved=await saveWebsitePreview(reference.data.projectId,reference.data.versionId,metadata.data,previewUrl,reference.data.deliverableId);refresh(reference.data.projectId,reference.data.versionId);return{status:"success",message:reference.data.deliverableId?"Preview website modifiée.":"Preview website ajoutée.",id:saved.id}}catch(error){return errorState(error instanceof DeliverablePreviewError?error:error)}}
