"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/guards";
import type { ActionState } from "@/features/versions/types";
import { previewMetadataSchema, previewReferenceSchema } from "./validation";
import { DeliverablePreviewError, saveVideoPreview, saveWebsitePreview } from "./operations";

function refresh(projectId:string,versionId:string){revalidatePath(`/admin/projects/${projectId}`);revalidatePath(`/admin/projects/${projectId}/versions/${versionId}`);revalidatePath(`/client/projects/${projectId}`);revalidatePath(`/client/projects/${projectId}/versions/${versionId}`)}
function errorState(error:unknown):ActionState{return{status:"error",message:error instanceof Error?error.message:"L’enregistrement de la preview a échoué."}}
export async function uploadVideoPreview(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const reference=previewReferenceSchema.safeParse(Object.fromEntries(formData.entries()));const metadata=previewMetadataSchema.safeParse(Object.fromEntries(formData.entries()));if(!reference.success||!metadata.success)return{status:"error",message:"Informations invalides."};const file=formData.get("previewFile");if(!(file instanceof File))return{status:"error",message:"Fichier preview requis."};try{const saved=await saveVideoPreview(reference.data.projectId,reference.data.versionId,metadata.data,file,reference.data.deliverableId);refresh(reference.data.projectId,reference.data.versionId);return{status:"success",message:reference.data.deliverableId?"Preview vidéo remplacée.":"Preview vidéo ajoutée.",id:saved.id}}catch(error){return errorState(error)}}
export async function saveWebsitePreviewAction(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const reference=previewReferenceSchema.safeParse(Object.fromEntries(formData.entries()));const metadata=previewMetadataSchema.safeParse(Object.fromEntries(formData.entries()));const previewUrl=formData.get("previewUrl");if(!reference.success||!metadata.success||typeof previewUrl!=="string")return{status:"error",message:"Informations invalides."};try{const saved=await saveWebsitePreview(reference.data.projectId,reference.data.versionId,metadata.data,previewUrl,reference.data.deliverableId);refresh(reference.data.projectId,reference.data.versionId);return{status:"success",message:reference.data.deliverableId?"Preview website modifiée.":"Preview website ajoutée.",id:saved.id}}catch(error){return errorState(error instanceof DeliverablePreviewError?error:error)}}
