import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, stat } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";
import { commitStagedFile, previewStorageKey, privateStorageRoot, removePrivateFile, resolvePrivateStorageKey, stagePrivateFile } from "@/lib/storage/private-storage";
import { canReadPreview, isPreviewVisibleToClient } from "./policy";
import { createPrivatePreviewResponse } from "./stream";
import { maxPreviewBytes, sanitizeFileName, validateVideoFile, validateWebsiteUrl } from "./validation";
import { saveVideoPreview, saveWebsitePreview } from "./operations";

const prisma=new PrismaClient();
test("stockage privé, traversal, écriture atomique et Range sécurisé",async()=>{const previous=process.env.PRIVATE_STORAGE_ROOT;delete process.env.PRIVATE_STORAGE_ROOT;assert.throws(()=>privateStorageRoot());const root=await mkdtemp(path.join(os.tmpdir(),"digit-preview-"));process.env.PRIVATE_STORAGE_ROOT=root;try{assert.throws(()=>resolvePrivateStorageKey("../../secret"));assert.throws(()=>resolvePrivateStorageKey("/etc/passwd"));const key=previewStorageKey("project1","version1","deliverable1",".mp4");assert.match(key,/^projects\/project1\/versions\/version1\/previews\/deliverable1\//);const temp=await stagePrivateFile(new Uint8Array([0,1,2,3,4,5,6,7,8,9]));await commitStagedFile(temp,key);assert.deepEqual([...await readFile(resolvePrivateStorageKey(key))],[0,1,2,3,4,5,6,7,8,9]);assert.equal(resolvePrivateStorageKey(key).startsWith(path.resolve("public")),false);const response=await createPrivatePreviewResponse(key,"video/mp4","bytes=2-5");assert.equal(response.status,206);assert.equal(response.headers.get("content-range"),"bytes 2-5/10");assert.equal(response.headers.get("content-length"),"4");assert.equal(response.headers.get("content-type"),"video/mp4");assert.equal(response.headers.get("content-disposition"),"inline");assert.equal(response.headers.get("cache-control"),"private, no-store");assert.equal(await response.text(),String.fromCharCode(2,3,4,5));assert.equal(JSON.stringify([...response.headers]).includes(root),false);await removePrivateFile(key);await assert.rejects(stat(resolvePrivateStorageKey(key)))}finally{process.env.PRIVATE_STORAGE_ROOT=previous}});

test("validation stricte MP4/WEBM, taille, noms et URL website",()=>{const previous=process.env.MAX_PREVIEW_UPLOAD_MB;process.env.MAX_PREVIEW_UPLOAD_MB="1";try{assert.equal(maxPreviewBytes(),1048576);assert.equal(validateVideoFile(new File([new Uint8Array([1])],"preview.mp4",{type:"video/mp4"})).extension,".mp4");assert.equal(validateVideoFile(new File([new Uint8Array([1])],"preview.webm",{type:"video/webm"})).mimeType,"video/webm");assert.throws(()=>validateVideoFile(new File([],"vide.mp4",{type:"video/mp4"})));assert.throws(()=>validateVideoFile(new File([new Uint8Array(1048577)],"gros.mp4",{type:"video/mp4"})));assert.throws(()=>validateVideoFile(new File([new Uint8Array([1])],"virus.exe",{type:"video/mp4"})));assert.throws(()=>validateVideoFile(new File([new Uint8Array([1])],"page.html",{type:"text/html"})));assert.equal(sanitizeFileName("../../vidéo<script>.mp4").includes("/"),false);assert.equal(validateWebsiteUrl("https://preview.example.com/").startsWith("https://"),true);for(const url of ["javascript:alert(1)","data:text/html,x","file:///secret","ftp://example.com/a"])assert.throws(()=>validateWebsiteUrl(url))}finally{process.env.MAX_PREVIEW_UPLOAD_MB=previous}});

test("permissions preview Admin/Client et publication par VersionStatus",()=>{assert.equal(canReadPreview("ADMIN","admin","other","DRAFT"),true);assert.equal(canReadPreview("CLIENT","client","client","DRAFT"),false);assert.equal(canReadPreview("CLIENT","client","client","READY_FOR_REVIEW"),true);assert.equal(canReadPreview("CLIENT","other","client","APPROVED"),false);assert.equal(isPreviewVisibleToClient("APPROVED"),true);assert.equal(isPreviewVisibleToClient("FINAL"),true);assert.equal(isPreviewVisibleToClient("DRAFT"),false)});

test("uploads PostgreSQL, remplacement sûr, website et compatibilité ancien livrable",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"digit-preview-db-"));const previous=process.env.PRIVATE_STORAGE_ROOT;process.env.PRIVATE_STORAGE_ROOT=root;const ids:{users:string[];project?:string;version?:string;service?:string}={users:[]};try{const suffix=Date.now().toString();const passwordHash=await bcrypt.hash("PasswordTest123!",4);const client=await prisma.user.create({data:{name:"Client preview",phone:`+24382${suffix.slice(-8)}`,passwordHash,role:"CLIENT"}});ids.users.push(client.id);const project=await prisma.project.create({data:{name:"Preview test",type:"AD_VIDEO",clientId:client.id}});ids.project=project.id;const version=await prisma.projectVersion.create({data:{projectId:project.id,versionNumber:1,name:"V1"}});ids.version=version.id;const first=await saveVideoPreview(project.id,version.id,{name:"Spot"},new File([new Uint8Array([1,2,3])],"spot.mp4",{type:"video/mp4"}));const before=await prisma.deliverable.findUniqueOrThrow({where:{id:first.id}});assert.equal(before.previewKind,"FILE");assert.equal(before.fileUrl,null);assert.ok(before.previewStorageKey);assert.deepEqual([...await readFile(resolvePrivateStorageKey(before.previewStorageKey!))],[1,2,3]);await assert.rejects(saveVideoPreview(project.id,version.id,{name:"Spot"},new File([new Uint8Array([9])],"virus.exe",{type:"video/mp4"}),first.id));assert.deepEqual([...await readFile(resolvePrivateStorageKey(before.previewStorageKey!))],[1,2,3]);await saveVideoPreview(project.id,version.id,{name:"Spot remplacé"},new File([new Uint8Array([4,5])],"spot.webm",{type:"video/webm"}),first.id);const after=await prisma.deliverable.findUniqueOrThrow({where:{id:first.id}});assert.notEqual(after.previewStorageKey,before.previewStorageKey);await assert.rejects(stat(resolvePrivateStorageKey(before.previewStorageKey!)));assert.deepEqual([...await readFile(resolvePrivateStorageKey(after.previewStorageKey!))],[4,5]);const website=await saveWebsitePreview(project.id,version.id,{name:"Staging"},"https://preview.example.com");assert.equal((await prisma.deliverable.findUniqueOrThrow({where:{id:website.id}})).previewKind,"EXTERNAL_URL");const legacy=await prisma.deliverable.create({data:{name:"Legacy",type:"DOCUMENT",fileName:"legacy.pdf",fileUrl:"https://legacy.example.com/file",versionId:version.id}});assert.equal((await prisma.deliverable.findUniqueOrThrow({where:{id:legacy.id}})).previewKind,null)}finally{if(ids.project)await prisma.project.deleteMany({where:{id:ids.project}});await prisma.user.deleteMany({where:{id:{in:ids.users}}});process.env.PRIVATE_STORAGE_ROOT=previous}});
test.after(async()=>{await prisma.$disconnect()});
