import Link from "next/link";
import {prisma} from "@/lib/prisma";
import {orderStatusLabels} from "@/features/admin-orders/labels";
import {projectStatusLabels} from "@/features/projects/labels";
const card="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,.03)]";
export default async function AdminPage(){
  const [activeClients,ordersToProcess,activeProjects,paymentsToReview,recentOrders,projectActions,openRequests,emailFailed,whatsAppFailed]=await Promise.all([
    prisma.user.count({where:{role:"CLIENT",isActive:true}}),
    prisma.order.count({where:{status:{in:["NEW","UNDER_REVIEW","NEEDS_INFORMATION","QUOTED"]}}}),
    prisma.project.count({where:{status:{not:"DELIVERED"}}}),
    prisma.payment.count({where:{status:{in:["SUBMITTED","UNDER_REVIEW"]}}}),
    prisma.order.findMany({select:{id:true,orderNumber:true,title:true,status:true,createdAt:true,client:{select:{name:true}}},orderBy:{createdAt:"desc"},take:5}),
    prisma.project.findMany({where:{status:{in:["REVIEW","CHANGES_REQUESTED","APPROVED","PAYMENT_PENDING","READY_FOR_DELIVERY"]}},select:{id:true,name:true,status:true,client:{select:{name:true}}},orderBy:{updatedAt:"desc"},take:5}),
    prisma.modificationRequest.count({where:{status:{in:["PENDING","IN_PROGRESS"]}}}),prisma.emailOutbox.count({where:{status:"FAILED"}}),prisma.whatsAppOutbox.count({where:{status:"FAILED"}}),
  ]);
  const kpis=[["Clients actifs",activeClients,"/admin/clients?status=active"],["Commandes à traiter",ordersToProcess,"/admin/orders?status=NEW"],["Projets en cours",activeProjects,"/admin/projects"],["Paiements à valider",paymentsToReview,"/admin/payments?status=SUBMITTED"]] as const;
  const priorities=[["Demandes de modification ouvertes",openRequests,"/admin/requests?status=PENDING"],["Paiements soumis ou en vérification",paymentsToReview,"/admin/payments?status=SUBMITTED"],["Emails en échec",emailFailed,"/admin/emails?status=FAILED"],["WhatsApp en échec",whatsAppFailed,"/admin/whatsapp"]] as const;
  return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><p className="text-xs font-bold tracking-[.18em] text-teal-700">ADMINISTRATION</p><h1 className="mt-2 text-3xl font-black text-slate-950">Tableau de bord</h1><p className="mt-2 text-slate-600">Vue opérationnelle de l’activité DigIT Agency.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label,value,href])=><Link key={label} href={href} className={card}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></Link>)}</section><section className="mt-10"><h2 className="text-xl font-black text-slate-950">À traiter</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{priorities.map(([label,value,href])=><Link key={label} href={href} className={`rounded-xl border p-4 ${value?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}><span className="text-2xl font-black text-slate-950">{value}</span><p className="mt-1 text-sm text-slate-600">{label}</p></Link>)}</div></section><div className="mt-10 grid gap-8 xl:grid-cols-2"><section><div className="flex items-center justify-between"><h2 className="text-xl font-black">Dernières commandes</h2><Link href="/admin/orders" className="text-sm font-bold text-teal-700">Voir toutes →</Link></div><div className="mt-4 space-y-3">{recentOrders.map(order=><Link key={order.id} href={`/admin/orders/${order.id}`} className={`${card} flex items-center justify-between gap-4`}><span className="min-w-0"><strong className="block truncate">{order.orderNumber} · {order.title}</strong><small className="text-slate-500">{order.client.name} · {order.createdAt.toLocaleDateString("fr-FR")}</small></span><span className="text-xs font-bold text-teal-700">{orderStatusLabels[order.status]}</span></Link>)}</div></section><section><div className="flex items-center justify-between"><h2 className="text-xl font-black">Projets nécessitant une action</h2><Link href="/admin/projects" className="text-sm font-bold text-teal-700">Voir tous →</Link></div><div className="mt-4 space-y-3">{projectActions.map(project=><Link key={project.id} href={`/admin/projects/${project.id}`} className={`${card} flex items-center justify-between gap-4`}><span className="min-w-0"><strong className="block truncate">{project.name}</strong><small className="text-slate-500">{project.client.name}</small></span><span className="text-xs font-bold text-teal-700">{projectStatusLabels[project.status]}</span></Link>)}{!projectActions.length&&<p className={`${card} text-sm text-slate-500`}>Aucun projet ne nécessite d’action immédiate.</p>}</div></section></div></main>;
}
