import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { findActiveServiceBySlug } from "@/features/public-services/queries";
import { formatServicePrice } from "@/features/services/labels";
import { serviceWhatsAppUrl } from "@/lib/whatsapp";
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const service=await findActiveServiceBySlug(slug);if(!service)return{title:"Service introuvable | DigIT Agency"};return{title:`${service.name} | DigIT Agency`,description:service.shortDescription};}
export default async function ServicePage({params}:Props){const{slug}=await params;const service=await findActiveServiceBySlug(slug);if(!service)notFound();return <main className="text-white"><section className="border-b border-white/10 bg-graphite-secondary"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><Link href="/services" className="text-sm font-bold text-electric-mint">← Tous les services</Link><p className="mt-10 text-sm font-bold uppercase tracking-[.2em] text-electric-mint">{service.category}</p><h1 className="mt-4 text-5xl font-black">{service.name}</h1><p className="mt-6 text-xl leading-8 text-muted">{service.shortDescription}</p><p className="mt-7 text-2xl font-black">{formatServicePrice(service.priceType,service.basePrice,service.currency)}</p><div className="mt-8 flex flex-wrap gap-4"><Link href={`/order?service=${encodeURIComponent(service.slug)}`} className="rounded-xl bg-electric-mint px-6 py-3 font-bold text-graphite">Commander ce service</Link><a href={serviceWhatsAppUrl(service.name)} target="_blank" rel="noreferrer" className="rounded-xl border border-white/20 px-6 py-3 font-bold">WhatsApp</a></div></div>{service.imageUrl?<div role="img" aria-label={`Illustration de ${service.name}`} className="min-h-80 rounded-3xl bg-cover bg-center" style={{backgroundImage:`url(${service.imageUrl})`}}/>:<div className="grid min-h-80 place-items-center rounded-3xl border border-electric-mint/20 bg-[radial-gradient(circle,rgba(0,229,184,.18),transparent_60%)]"><span className="text-8xl font-black text-electric-mint/50">D</span></div>}</div></section><section className="mx-auto max-w-4xl px-5 py-20 lg:px-8"><h2 className="text-3xl font-black">À propos de ce service</h2><div className="mt-7 whitespace-pre-wrap text-lg leading-9 text-muted">{service.description}</div></section></main>}
