import type { Metadata } from "next";
import Link from "next/link";
import { ServiceCard } from "@/components/public/service-card";
import { findHomepageServices } from "@/features/public-services/queries";
import { generalWhatsAppUrl } from "@/lib/whatsapp";

export const metadata: Metadata = { title: "DigIT Agency | Solutions digitales et technologiques", description: "Des solutions digitales et technologiques conçues pour faire grandir votre entreprise." };

export default async function HomePage() {
  const services = await findHomepageServices();
  return <main className="text-white">
    <section className="relative overflow-hidden border-b border-white/10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(0,229,184,.17),transparent_32%)]"/><div className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-5 py-24 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.24em] text-electric-mint">TECHNOLOGIE · STRATÉGIE · CROISSANCE</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[1.05] sm:text-6xl lg:text-7xl">Des solutions digitales et technologiques conçues pour faire grandir votre entreprise.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">DigIT Agency conçoit des outils performants et accompagne les organisations dans leur évolution numérique, de l’idée à une solution concrète et durable.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/order" className="rounded-xl bg-electric-mint px-6 py-3.5 font-bold text-graphite">Commander un service</Link><a href={generalWhatsAppUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-white/20 px-6 py-3.5 font-bold">Parler sur WhatsApp</a></div></div><div className="hidden lg:block"><div className="relative aspect-square rounded-[3rem] border border-white/10 bg-graphite-secondary p-8"><div className="absolute inset-8 rounded-[2.5rem] border border-electric-mint/20"/><div className="absolute left-16 top-16 h-24 w-24 rounded-3xl bg-electric-mint/20"/><div className="absolute bottom-20 right-16 h-40 w-40 rounded-full border border-electric-mint/40"/><p className="absolute bottom-14 left-14 max-w-xs text-2xl font-black">Construire aujourd’hui les capacités technologiques de demain.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold tracking-[.2em] text-electric-mint">NOS SERVICES</p><h2 className="mt-3 text-4xl font-black">Des expertises qui produisent des résultats</h2></div><Link href="/services" className="font-bold text-electric-mint">Voir tous les services →</Link></div>{services.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map(service=><ServiceCard key={service.id} service={service}/>)}</div> : <p className="mt-10 rounded-2xl border border-white/10 p-8 text-muted">Notre catalogue sera disponible prochainement.</p>}</section>
    <section className="bg-graphite-secondary"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-sm font-bold tracking-[.2em] text-electric-mint">POURQUOI DIGIT</p><h2 className="mt-3 text-4xl font-black">Une technologie utile, pensée pour votre réalité</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Vision globale","Nous relions stratégie, expérience utilisateur et choix techniques."],["Exécution claire","Des étapes lisibles, des échanges directs et des livrables maîtrisés."],["Solutions évolutives","Des fondations capables d’accompagner votre activité dans le temps."]].map(([title,text],index)=><article key={title} className="rounded-2xl border border-white/10 bg-graphite p-6"><span className="text-sm font-black text-electric-mint">0{index+1}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-muted">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-sm font-bold tracking-[.2em] text-electric-mint">NOTRE MÉTHODE</p><div className="mt-4 grid gap-10 lg:grid-cols-2"><h2 className="text-4xl font-black">De votre besoin à une solution déployable.</h2><ol className="grid gap-5">{["Comprendre les enjeux et les utilisateurs","Définir une réponse claire et mesurable","Concevoir, développer et valider","Accompagner l’évolution de la solution"].map((step,index)=><li key={step} className="flex gap-4 border-b border-white/10 pb-5"><span className="font-black text-electric-mint">{index+1}</span><span className="font-semibold">{step}</span></li>)}</ol></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="rounded-3xl border border-electric-mint/30 bg-[linear-gradient(120deg,rgba(0,229,184,.13),rgba(26,31,38,.8))] p-8 sm:p-12"><h2 className="max-w-3xl text-4xl font-black">Votre prochain projet mérite une base technologique solide.</h2><p className="mt-4 text-muted">Découvrez nos services ou échangez directement avec notre équipe.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/order" className="rounded-xl bg-electric-mint px-6 py-3 font-bold text-graphite">Commander un service</Link><Link href="/contact" className="rounded-xl border border-white/20 px-6 py-3 font-bold">Nous contacter</Link></div></div></section>
  </main>;
}
