import Link from "next/link";
import { notFound } from "next/navigation";
import { ApprovalForm } from "./approval-form";
import { RequestForm } from "./request-form";
import { requireClient } from "@/lib/auth/guards";
import { clientVersionStatusLabels, fileSizeLabel } from "@/features/client-portal/labels";
import { findClientVersion } from "@/features/client-portal/queries";
import { projectIdSchema } from "@/features/projects/validation";
import { idSchema } from "@/features/versions/validation";
import { canRequestModification } from "@/features/version-approvals/policy";
import { isPreviewVisibleToClient } from "@/features/deliverable-previews/policy";

export default async function ClientVersionPage({params}:{params:Promise<{id:string;versionId:string}>}){const client=await requireClient();const{id,versionId}=await params;if(!projectIdSchema.safeParse(id).success||!idSchema.safeParse(versionId).success)notFound();const version=await findClientVersion(client.id,id,versionId);if(!version)notFound();const previewsVisible=isPreviewVisibleToClient(version.status);return <main className="mx-auto max-w-5xl px-5 py-10 text-white"><Link href={`/client/projects/${id}`} className="text-sm font-medium text-electric-mint">← {version.project.name}</Link><p className="mt-7 text-sm font-semibold tracking-[.18em] text-electric-mint">VERSION {version.versionNumber}</p><h1 className="mt-3 text-3xl font-bold">{version.name}</h1><p className="mt-2 text-muted">{clientVersionStatusLabels[version.status]} · {version.createdAt.toLocaleDateString("fr-FR")}</p><p className="mt-6 whitespace-pre-wrap">{version.description||"Aucune description disponible."}</p>
  {version.approval?<section className="mt-8 rounded-2xl border border-electric-mint/40 bg-electric-mint/10 p-6"><h2 className="text-xl font-bold text-electric-mint">Version approuvée</h2><p className="mt-2">Vous avez approuvé cette version le {version.approval.approvedAt.toLocaleDateString("fr-FR",{dateStyle:"long"})}.</p><p className="mt-2 text-muted">Le projet est maintenant en attente de l’étape suivante.</p></section>:version.status==="READY_FOR_REVIEW"?<section className="mt-8 rounded-2xl border border-electric-mint/40 bg-graphite-secondary p-6"><h2 className="text-xl font-bold">Cette version est prête pour votre validation.</h2><ApprovalForm projectId={id} versionId={version.id}/></section>:version.status==="CHANGES_REQUESTED"?<section className="mt-8 rounded-2xl border border-amber-300/30 bg-amber-300/5 p-6"><h2 className="text-xl font-bold">Vous avez demandé des modifications sur cette version.</h2><p className="mt-2 text-muted">DigIT Agency prépare une nouvelle version.</p></section>:null}
  <section className="mt-10"><h2 className="text-2xl font-bold">Livrables</h2><div className="mt-5 space-y-4">{version.deliverables.map(d=><article key={d.id} className="rounded-2xl border border-white/10 bg-graphite-secondary p-5"><h3 className="font-bold">{d.name}</h3><p className="mt-2 text-sm text-muted">{d.description||"Aucune description disponible."}</p>{previewsVisible&&d.previewKind==="FILE"&&d.type==="VIDEO"?<div className="mt-5"><video controls preload="metadata" controlsList="nodownload" disablePictureInPicture className="w-full rounded-xl bg-black" src={`/api/deliverables/${d.id}/preview`}/><p className="mt-2 text-xs text-muted">Preview sécurisée · {d.previewFileName} · {fileSizeLabel(d.previewFileSize)}</p></div>:previewsVisible&&d.previewKind==="EXTERNAL_URL"&&d.type==="WEBSITE"&&d.previewUrl?<div className="mt-5 rounded-xl border border-white/10 p-4"><p>Aperçu du site disponible</p><a href={d.previewUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block rounded-lg bg-electric-mint px-4 py-2 font-semibold text-graphite">Voir le site de prévisualisation</a></div>:<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-muted">Fichier</dt><dd>{d.fileName}</dd></div><div><dt className="text-muted">Type</dt><dd>{d.type}</dd></div><div><dt className="text-muted">Taille</dt><dd>{fileSizeLabel(d.fileSize)}</dd></div><div className="sm:col-span-3"><dt className="text-muted">Disponibilité</dt><dd>Preview non publiée ou ancien livrable.</dd></div></dl>}</article>)}{!version.deliverables.length&&<p className="rounded-xl border border-dashed border-white/15 p-5 text-muted">Aucun livrable n’est encore disponible.</p>}</div></section>
  <section className="mt-10"><h2 className="text-2xl font-bold">Demandes de modification</h2>{canRequestModification(version.status)?<RequestForm projectId={id} versionId={version.id}/>:<p className="mt-4 rounded-xl border border-white/10 bg-white/5 p-4 text-muted">Cette version approuvée ne peut plus recevoir de nouvelle demande. Les demandes précédentes restent disponibles ci-dessous.</p>}<div className="mt-5 space-y-3">{version.modificationRequests.map(r=><article key={r.id} className="rounded-xl border border-white/10 bg-graphite-secondary p-5"><strong>{r.title}</strong><p className="mt-2 text-sm text-muted">{r.description}</p><p className="mt-3 text-sm text-electric-mint">{r.status}</p>{r.adminResponse&&<p className="mt-3 rounded-lg bg-white/5 p-3 text-sm">Réponse DigIT Agency : {r.adminResponse}</p>}</article>)}{!version.modificationRequests.length&&<p className="mt-5 rounded-xl border border-dashed border-white/15 p-5 text-muted">Aucune demande de modification.</p>}</div></section>
</main>}
