import Link from "next/link";
import { notFound } from "next/navigation";
import { ApprovalForm } from "./approval-form";
import { RequestForm } from "./request-form";
import { requireClient } from "@/lib/auth/guards";
import { fileSizeLabel } from "@/features/client-portal/labels";
import { findClientVersion } from "@/features/client-portal/queries";
import { projectIdSchema } from "@/features/projects/validation";
import { idSchema } from "@/features/versions/validation";
import { canRequestModification } from "@/features/version-approvals/policy";
import { isPreviewVisibleToClient } from "@/features/deliverable-previews/policy";
import { StatusBadge } from "@/components/client/status-badge";
import { EmptyState } from "@/components/client/empty-state";

export default async function ClientVersionPage({params}:{params:Promise<{id:string;versionId:string}>}) {
  const client=await requireClient(); const {id,versionId}=await params;
  if(!projectIdSchema.safeParse(id).success||!idSchema.safeParse(versionId).success)notFound();
  const version=await findClientVersion(client.id,id,versionId); if(!version)notFound();
  const previewsVisible=isPreviewVisibleToClient(version.status);
  return <main className="mx-auto max-w-6xl px-5 py-10 lg:px-8">
    <Link href={`/client/projects/${id}`} className="text-sm font-bold text-teal-700">← {version.project.name}</Link>
    <header className="mt-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-teal-600">VERSION {version.versionNumber}</p><h1 className="mt-2 text-3xl font-black text-slate-950">{version.name}</h1><p className="mt-2 text-sm text-slate-500">Créée le {version.createdAt.toLocaleDateString("fr-FR")}</p></div><StatusBadge kind="version" status={version.status}/></header>
    <p className="mt-6 max-w-3xl whitespace-pre-wrap text-slate-700">{version.description||"Aucune description disponible."}</p>
    {version.approval?<section className="mt-8 rounded-xl border border-teal-200 bg-teal-50 p-6"><h2 className="text-xl font-black text-teal-900">Version approuvée</h2><p className="mt-2 text-slate-700">Vous avez approuvé cette version le {version.approval.approvedAt.toLocaleDateString("fr-FR",{dateStyle:"long"})}. Le projet passe à l’étape suivante.</p></section>:version.status==="READY_FOR_REVIEW"?<section className="mt-8 rounded-xl border border-teal-200 bg-white p-6"><h2 className="text-xl font-black text-slate-950">Cette version est prête pour votre validation.</h2><p className="mt-2 text-slate-600">Examinez les aperçus ci-dessous avant de confirmer.</p><ApprovalForm projectId={id} versionId={version.id}/></section>:version.status==="CHANGES_REQUESTED"?<section className="mt-8 rounded-xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-black text-amber-900">Modifications demandées</h2><p className="mt-2 text-amber-800">DigIT Agency prépare une nouvelle version.</p></section>:null}
    <section className="mt-10"><h2 className="text-2xl font-black text-slate-950">Livrables et aperçus</h2><div className="mt-5 space-y-4">{version.deliverables.map((item)=><article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{item.name}</h3><p className="mt-2 text-sm text-slate-600">{item.description||"Aucune description disponible."}</p>{previewsVisible&&item.previewKind==="FILE"&&item.type==="VIDEO"?<div className="mt-5"><video controls preload="metadata" controlsList="nodownload" disablePictureInPicture className="aspect-video w-full rounded-xl bg-black object-contain" src={`/api/deliverables/${item.id}/preview`}/><p className="mt-2 text-xs text-slate-500">Prévisualisation sécurisée · {item.previewFileName} · {fileSizeLabel(item.previewFileSize)}</p></div>:previewsVisible&&item.previewKind==="EXTERNAL_URL"&&item.type==="WEBSITE"&&item.previewUrl?<div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-slate-700">Aperçu du site disponible</p><a href={item.previewUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block rounded-lg bg-electric-mint px-4 py-2 font-bold text-slate-950">Voir le site de prévisualisation</a></div>:<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Fichier</dt><dd className="text-slate-800">{item.fileName}</dd></div><div><dt className="text-slate-500">Type</dt><dd className="text-slate-800">{item.type}</dd></div><div><dt className="text-slate-500">Taille</dt><dd className="text-slate-800">{fileSizeLabel(item.fileSize)}</dd></div><div className="sm:col-span-3"><dt className="text-slate-500">Disponibilité</dt><dd className="text-slate-800">Prévisualisation non publiée ou ancien livrable.</dd></div></dl>}</article>)}{!version.deliverables.length&&<EmptyState title="Aucun livrable disponible" description="Les aperçus apparaîtront ici dès leur publication."/>}</div></section>
    <section className="mt-10"><h2 className="text-2xl font-black text-slate-950">Demandes de modification</h2>{canRequestModification(version.status)?<RequestForm projectId={id} versionId={version.id}/>:<p className="mt-4 rounded-xl border border-slate-200 bg-white p-4 text-slate-600">Cette version approuvée ne peut plus recevoir de nouvelle demande. L’historique reste disponible ci-dessous.</p>}<div className="mt-5 space-y-3">{version.modificationRequests.map((request)=><article key={request.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><strong className="text-slate-950">{request.title}</strong><span className="text-xs font-bold text-teal-700">{request.status}</span></div><p className="mt-2 text-sm text-slate-600">{request.description}</p>{request.adminResponse&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Réponse DigIT Agency :</strong> {request.adminResponse}</p>}</article>)}{!version.modificationRequests.length&&<EmptyState title="Aucune demande de modification" description="Vos demandes liées à cette version apparaîtront ici."/>}</div></section>
  </main>;
}
