import { Readable } from "node:stream";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/options";
import { prisma } from "@/lib/prisma";
import { parseByteRange, privateFileInfo, privateFileStream } from "@/lib/storage/private-storage";
import { canReadPreview } from "@/features/deliverable-previews/policy";

export const runtime="nodejs";
const securityHeaders={"Accept-Ranges":"bytes","Cache-Control":"private, no-store","Content-Disposition":"inline","X-Content-Type-Options":"nosniff","Cross-Origin-Resource-Policy":"same-origin"};
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const session=await getServerSession(authOptions);if(!session?.user)return new Response("Non authentifié",{status:401});const{id}=await params;const deliverable=await prisma.deliverable.findUnique({where:{id},select:{previewKind:true,previewStorageKey:true,previewMimeType:true,version:{select:{status:true,project:{select:{clientId:true}}}}}});if(!deliverable||deliverable.previewKind!=="FILE"||!deliverable.previewStorageKey||!deliverable.previewMimeType)return new Response("Introuvable",{status:404});if(!canReadPreview(session.user.role,session.user.id,deliverable.version.project.clientId,deliverable.version.status))return new Response("Interdit",{status:403});try{const file=await privateFileInfo(deliverable.previewStorageKey);const range=parseByteRange(request.headers.get("range"),file.size);if(range==="invalid")return new Response(null,{status:416,headers:{...securityHeaders,"Content-Range":`bytes */${file.size}`}});const selected=range??{start:0,end:file.size-1};const length=selected.end-selected.start+1;const stream=privateFileStream(file.absolutePath,range??undefined);return new Response(Readable.toWeb(stream) as ReadableStream,{status:range?206:200,headers:{...securityHeaders,"Content-Type":deliverable.previewMimeType,"Content-Length":String(length),...(range?{"Content-Range":`bytes ${selected.start}-${selected.end}/${file.size}`}:{})}})}catch{return new Response("Introuvable",{status:404})}}
