import Link from "next/link";
import { notFound } from "next/navigation";
import { DeliverableForm } from "./deliverable-form";
import { VideoPreviewForm, WebsitePreviewForm } from "./preview-forms";
import { VersionForm } from "../version-form";
import { idSchema } from "@/features/versions/validation";
import { prisma } from "@/lib/prisma";

const labels={DRAFT:"Brouillon",READY_FOR_REVIEW:"Prête à réviser",APPROVED:"Approuvée",CHANGES_REQUESTED:"Modifications demandées",FINAL:"Finale"}as const;
export default async function VersionDetailPage({params}:{params:Promise<{id:string;versionId:string}>}){const{id,versionId}=await params;if(!idSchema.safeParse(id).success||!idSchema.safeParse(versionId).success)notFound();const version=await prisma.projectVersion.findFirst({where:{id:versionId,projectId:id},include:{project:{select:{name:true}},deliverables:{orderBy:{createdAt:"desc"}},approval:{include:{client:{select:{name:true,phone:true}}}}}});if(!version)notFound();return <main className="mx-auto max-w-4xl px-6 py-12 text-white"><Link href={`/admin/projects/${id}`} className="text-sm text-electric-mint">← {version.project.name}</Link><p className="mt-7 text-sm font-semibold tracking-[.18em] text-electric-mint">VERSION {version.versionNumber}</p><h1 className="mt-3 text-4xl font-bold">{version.name}</h1><p className="mt-2 text-muted">Statut : {labels[version.status]}</p>
  <section className="mt-8 rounded-2xl border border-white/10 bg-graphite-secondary p-5"><h2 className="text-lg font-bold">Approbation Client</h2>{version.approval?<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted">État</dt><dd className="text-electric-mint">Version approuvée</dd></div><div><dt className="text-muted">Date</dt><dd>{version.approval.approvedAt.toLocaleString("fr-FR")}</dd></div><div className="sm:col-span-2"><dt className="text-muted">Client</dt><dd>{version.approval.client.name} · {version.approval.client.phone}</dd></div></dl>:<p className="mt-3 text-muted">Cette version n’a pas été approuvée par le Client.</p>}</section>
  <section className="mt-10"><h2 className="text-2xl font-bold">Modifier la version</h2><VersionForm projectId={id} version={version}/></section>
  <section className="mt-12"><h2 className="text-2xl font-bold">Livrables / Prévisualisations</h2><p className="mt-2 text-muted">Préparez les previews, puis passez la version à « Prête à réviser » pour les publier.</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="mb-3 font-semibold">Nouvelle preview vidéo</h3><VideoPreviewForm projectId={id} versionId={version.id}/></div><div><h3 className="mb-3 font-semibold">Nouvelle preview website</h3><WebsitePreviewForm projectId={id} versionId={version.id}/></div></div><details className="mt-5 rounded-xl border border-white/10 p-4"><summary className="cursor-pointer text-sm text-muted">Ajouter un ancien livrable de métadonnées</summary><DeliverableForm projectId={id} versionId={version.id}/></details><div className="mt-6 space-y-4">{version.deliverables.map(item=><article key={item.id} className="rounded-xl border border-white/10 bg-graphite-secondary p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{item.name}</h3><p className="text-sm text-muted">{item.type} · {item.previewKind??"Ancien livrable"} · {item.createdAt.toLocaleDateString("fr-FR")}</p></div><p className="text-sm text-muted">{item.previewFileSize?`${(item.previewFileSize/(1024*1024)).toFixed(1)} Mo · ${item.previewMimeType}`:item.previewUrl?"URL staging":"Aucune preview privée"}</p></div>{item.description&&<p className="mt-3 text-sm text-muted">{item.description}</p>}{item.previewKind==="FILE"&&<video controls preload="metadata" controlsList="nodownload" className="mt-4 w-full rounded-xl bg-black" src={`/api/deliverables/${item.id}/preview`}/>} {item.previewKind==="EXTERNAL_URL"&&item.previewUrl&&<a href={item.previewUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block text-electric-mint underline">Ouvrir le staging</a>}<details className="mt-4"><summary className="cursor-pointer text-sm text-electric-mint">Modifier ou remplacer</summary><div className="mt-3">{item.type==="VIDEO"?<VideoPreviewForm projectId={id} versionId={version.id} item={item}/>:item.type==="WEBSITE"?<WebsitePreviewForm projectId={id} versionId={version.id} item={item}/>:<DeliverableForm projectId={id} versionId={version.id} item={item}/>}</div></details></article>)}{!version.deliverables.length&&<p className="rounded-xl border border-dashed border-white/15 p-5 text-muted">Aucun livrable pour cette version.</p>}</div></section>
</main>}
