"use client";
import { useActionState } from "react";
import { saveWebsitePreviewAction, uploadVideoPreview } from "@/features/deliverable-previews/actions";
import { initialActionState } from "@/features/versions/types";

type Existing={id:string;name:string;description:string|null;previewUrl?:string|null};
function Message({state}:{state:typeof initialActionState}){return state.status!=="idle"?<p role="status" className={state.status==="success"?"text-sm text-electric-mint":"text-sm text-red-300"}>{state.message}</p>:null}
export function VideoPreviewForm({projectId,versionId,item}:{projectId:string;versionId:string;item?:Existing}){const[state,action,pending]=useActionState(uploadVideoPreview,initialActionState);return <form action={action} encType="multipart/form-data" className="grid gap-3 rounded-xl border border-white/10 p-4"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="versionId" value={versionId}/>{item&&<input type="hidden" name="deliverableId" value={item.id}/>}<input required name="name" defaultValue={item?.name??""} placeholder="Nom du livrable" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><textarea name="description" defaultValue={item?.description??""} placeholder="Description facultative" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><input required name="previewFile" type="file" accept="video/mp4,video/webm,.mp4,.webm" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><p className="text-xs text-muted">MP4 ou WEBM. Utilisez de préférence une version compressée et watermarkée.</p><Message state={state}/><button disabled={pending} className="w-fit rounded-lg bg-electric-mint px-4 py-2 text-sm font-semibold text-graphite disabled:opacity-60">{pending?"Téléversement…":item?"Remplacer la preview":"Ajouter la preview vidéo"}</button></form>}
export function WebsitePreviewForm({projectId,versionId,item}:{projectId:string;versionId:string;item?:Existing}){const[state,action,pending]=useActionState(saveWebsitePreviewAction,initialActionState);return <form action={action} className="grid gap-3 rounded-xl border border-white/10 p-4"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="versionId" value={versionId}/>{item&&<input type="hidden" name="deliverableId" value={item.id}/>}<input required name="name" defaultValue={item?.name??""} placeholder="Nom du livrable" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><textarea name="description" defaultValue={item?.description??""} placeholder="Description facultative" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><input required name="previewUrl" type="url" defaultValue={item?.previewUrl??""} placeholder="https://preview.example.com" className="rounded-lg border border-white/15 bg-graphite px-3 py-2"/><Message state={state}/><button disabled={pending} className="w-fit rounded-lg bg-electric-mint px-4 py-2 text-sm font-semibold text-graphite disabled:opacity-60">{pending?"Enregistrement…":item?"Modifier la preview":"Ajouter la preview website"}</button></form>}
