import Link from "next/link";
import { projectStatusLabels, projectTypeLabels, statusClass } from "@/features/projects/labels";
import { prisma } from "@/lib/prisma";

type PageProps = { searchParams: Promise<{ q?: string; type?: string; status?: string }> };

export default async function ProjectsPage({ searchParams }: PageProps) {
  const { q = "", type = "all", status = "all" } = await searchParams;
  const query = q.trim();
  const typeFilter = Object.hasOwn(projectTypeLabels, type) ? type as keyof typeof projectTypeLabels : undefined;
  const statusFilter = Object.hasOwn(projectStatusLabels, status) ? status as keyof typeof projectStatusLabels : undefined;
  const where = { ...(query ? { OR: [{ name: { contains: query, mode: "insensitive" as const } }, { client: { name: { contains: query, mode: "insensitive" as const } } }] } : {}), ...(typeFilter ? { type: typeFilter } : {}), ...(statusFilter ? { status: statusFilter } : {}) };
  const [projects, total, inProgress, review, delivered] = await Promise.all([prisma.project.findMany({ where, include: { client: { select: { name: true } } }, orderBy: { updatedAt: "desc" } }), prisma.project.count(), prisma.project.count({ where: { status: "IN_PROGRESS" } }), prisma.project.count({ where: { status: "REVIEW" } }), prisma.project.count({ where: { status: "DELIVERED" } })]);

  return <main className="mx-auto max-w-6xl px-6 py-12 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold tracking-[0.18em] text-electric-mint">PROJETS</p><h1 className="mt-3 text-4xl font-bold">Gestion des projets</h1></div><Link href="/admin/projects/new" className="rounded-xl bg-electric-mint px-5 py-3 font-semibold text-graphite">+ Nouveau projet</Link></div>
    <section className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Total", total], ["En cours", inProgress], ["En review", review], ["Livrés", delivered]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-graphite-secondary p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section>
    <form className="mt-10 grid gap-3 md:grid-cols-[1fr_auto_auto_auto]"><input name="q" defaultValue={q} placeholder="Rechercher un projet ou client" className="rounded-xl border border-white/15 bg-graphite-secondary px-4 py-3 outline-none focus:border-electric-mint" /><select name="type" defaultValue={type} className="rounded-xl border border-white/15 bg-graphite-secondary px-4 py-3"><option value="all">Tous les types</option>{Object.entries(projectTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select name="status" defaultValue={status} className="rounded-xl border border-white/15 bg-graphite-secondary px-4 py-3"><option value="all">Tous les statuts</option>{Object.entries(projectStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl border border-white/15 px-5 py-3 font-medium">Filtrer</button></form>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[1.3fr_1fr_1fr_1fr] gap-4 border-b border-white/10 bg-graphite-secondary px-5 py-4 text-xs font-semibold uppercase tracking-wide text-muted"><span>Projet</span><span>Client</span><span>Type</span><span>Statut</span></div>{projects.length ? projects.map((project) => <Link key={project.id} href={`/admin/projects/${project.id}`} className="grid grid-cols-[1.3fr_1fr_1fr_1fr] gap-4 border-b border-white/5 px-5 py-4 transition hover:bg-white/5"><span><strong className="block">{project.name}</strong><small className="text-muted">Mis à jour le {project.updatedAt.toLocaleDateString("fr-FR")}</small></span><span>{project.client.name}</span><span className="text-sm text-muted">{projectTypeLabels[project.type]}</span><span><small className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass(project.status)}`}>{projectStatusLabels[project.status]}</small></span></Link>) : <p className="p-8 text-muted">Aucun projet ne correspond aux critères.</p>}</section>
  </main>;
}
